[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "rtd_tutorial"
authors = [{name = "Anon", email = "anon@noemail.com"}]
dynamic = ["version", "description"]
